AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Event-driven SecOps Architecture: Parses CloudTrail logs from S3, triggers Lambda for IAM anomalies, sends SES Alert.'

Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket

  SecurityScannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: scanner.handler
      Runtime: python3.9
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref CloudTrailBucket
        - SESCrudPolicy:
            IdentityName: "security-alerts@company.com"
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref CloudTrailBucket
            Events: s3:ObjectCreated:*
