AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless SecOps Architecture: S3 trigger to Lambda for malware scanning.'
Resources:
  ScannerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
